site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/ros-bridge
docs_dir: docs
edit_uri: 'edit/master/docs/'
theme: readthedocs
extra_css: [extra.css]

nav:
- Home: 'index.md'
- Getting started:
  - Install ROS Bridge for ROS 1: 'ros_installation_ros1.md'
  - Install ROS Bridge for ROS 2: 'ros_installation_ros2.md'
  - The ROS bridge package: 'run_ros.md'
  - ROS Compatiblity Node: 'ros_compatibility.md'
- ROS Bridge Packages:
  - CARLA Spawn Objects: 'carla_spawn_objects.md'
  - CARLA Manual Control: 'carla_manual_control.md'
  - CARLA Waypoint Publisher: 'carla_waypoint.md'
  - CARLA Twist to Control: 'carla_twist_to_control.md'
  - RQT Plugin: 'rqt_plugin.md'
  - PCL Recorder: 'pcl_recorder.md'
- References:
  - CARLA sensor reference: 'ros_sensors.md'
  - CARLA messages reference: 'ros_msgs.md'

markdown_extensions:
  - admonition
